development:
  clients:
    default:
      database: mongo_blog_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: mongo_blog_test
      hosts:
        - localhost:27017
